name: 分享字体方案
description: 分享字体方案点这里,给插件提建议提问题点下面
title: "[字体方案分享] "
labels: ["字体方案分享"]
body:
  - type: markdown
    attributes:
      value: 请保留标题前缀 **[字体方案分享]**，后面填写字体方案名称、个人昵称、诗歌，或任何你想写的内容。
  - type: textarea
    id: description
    attributes:
      label: 字体方案介绍
      description: 将字体方案压缩包里readme.md中的表格粘贴到此,还可以写一些简单介绍哦.
  - type: textarea
    id: preview
    attributes:
      label: 效果截图
      description: (可选)将截图拖入输入框，展示字体方案效果.
  - type: textarea
    id: file
    attributes:
      label: 字体方案压缩包
      description: 将插件导出的 ZIP 拖入此处。gihub限制每个issue的附件最大为 25 MB. 如果体积超限,可以将字体文件转换为WOFF2格式或提供网盘链接.
    validations:
      required: true
